### ISSUE TITLE
Cannot find a matching dividend

### ISSUE THREAD

**Issue by mcsugaman** [jamsix/ib-edavki#100]
Hey guys, I installed ib-edavki from master and also from dividend-tax-conid branch, but I still get errors like: 
Cannot find a matching dividend for WELL(US95040Q1040) CASH DIVIDEND USD 0.61 PER SHARE - US TAX (20210819;202000) of -0.09.
Traceback (most recent call last):
  File "/home/jure/.local/bin/ib_edavki", line 8, in <module>
    sys.exit(main())
  File "/home/jure/.local/lib/python3.10/site-packages/ib_edavki.py", line 1198, in main
    closestDividend["taxEUR"] += closestDividendTax / getCurrencyRate(
UnboundLocalError: local variable 'closestDividend' referenced before assignment

I run the script with ib_edavki -y 2021 IZPIS_DAVKOMAT_si_ali_PYTHON_skripto.xml
What am I doing wrong? I also tried to delete problematic rows from IBKR file, but errors go on and on to other rows.
Thanks!

**Comment by ZigaSajovic** [comment]
Should be fixed by https://github.com/jamsix/ib-edavki/pull/101

**Comment by jamsix** [comment]
@mcsugaman try again with the latest version, @ZigaSajovic should have fixed this! Let us know.
