### ISSUE TITLE
Zaloga vrednostnih papirjev

### ISSUE THREAD

**Issue by RokLenarcic** [jamsix/ib-edavki#105]
V navodilih pise:
```
Preveri če vse pridobitve in odsvojitve ustrezajo dejanskim. Zaloga pri zadnjem vnosu mora biti 0.
```
Malo sem zmeden. Ce kupim 100 stocka in prodam 50, ali ne bi morala biti ta zaloga vrednosti 50? Ne razumem cisto kaj je funkcija tega polja v FURSovem obrazcu.

**Comment by jamsix** [comment]
Če v 2023 kupiš 100 in prodaš 50 delnic, potem si FURSu dolžan prijavit le del, ki si ga v 2023 prodal, ostalo jih ne zanima. Prijaviš torej 50 nakup, 50 prodaja in zaloga na koncu je 0.

**Comment by RokLenarcic** [comment]
Potem je to dosti nesmiselen podatek, ker je trivialno izracunljiv iz ostalih podatkov na listu, zato se mi je zdelo cudno. Ampak, ce se ne motim, pri pravilih navidezne odsvojitve je vazno, a si prodal vse ali pa ne, zato bi mislil, da je treba izpolnjevat te obrazce s pravimi zalogami vrednosti. Verjetno je najboljs vprasat FURS.

**Comment by jamsix** [comment]
Ta del FURS obračuna avtomatsko ne glede na stanje kljukice v oddanem obrazcu.
