### ISSUE TITLE
Dividende v csv obliki

### ISSUE THREAD

**Issue by mcsugaman** [jamsix/ib-edavki#111]
Pozdravljeni,

na edavkih bi rad uvozil datoteko Doh-Div.xml za napoved dobička od dividend, vendar je na portalu podprt samo uvoz CSV datotek.
Ali lahko skripta zgenerira tudi CSV datoteko? Obstaja kakšen način za pretvorbo XML datoteke v CSV, ki bi bila primerna za uvoz v edavke?

Hvala.

**Comment by pronebird** [comment]
Kva? A to neka nova zajebanca, ker v preteklosti xml je bila edina oblika za uvoz?

**Comment by hamihaa** [comment]
Sem ravno naletel na enak problem, piše:

"Uvoz podatkov o izplačevalcih dividend in izplačanih dividendah s csv datoteko"

**Comment by jamsix** [comment]
eDavki že nekaj let podpirajo XML in CSV format uvoza, UX je pa žal tak, da je vsak format za uvoz na voljo na drugem mestu in to seveda zmede uporabnika. Če boš sledil [navodilom](https://github.com/jamsix/ib-edavki/blob/master/README.md#uvoz-v-edavke) boš lahko uvozil XML.

**Comment by jamsix** [comment]
V README.md sem [dodal posnetek zaslona pravega uvoza in opozorilo o CSV obliki](https://github.com/jamsix/ib-edavki/pull/112). Upam, da bo sedaj glede tega manj zmede.
