### ISSUE TITLE
Doh-KDVP enchancement

### ISSUE THREAD

**Issue by ZiGaMi** [jamsix/ib-edavki#113]
Ali bi bilo smiselno dodati v generacijo "Doh-KDVP.xml" tudi datume pridobitve vrednostnih papirjev in FIFO metodo?

Vem, da to konkretno zakomplicira zadevo, saj bi si morali voditi že prijavljnene assete, torej bi si morala skripta "zapomniti" kaj je že prijavljeno in kaj ne. Razmišljam na glas, ker je zelo boleče to delati ročno :)

Kaj si mislite?

**Comment by jamsix** [comment]
V `Doh-KDVP.xml` so datumi pridobitve, to je obvezen element. `ib-edavki` so narejeni tako, da upoštevajo FIFO, pod pogojem, da slediš navodilom in kot vhodne podatke uporabiš IBKR XML poročila za vsa leta trgovanja.

**Comment by ZiGaMi** [comment]
OK, razumem.

Hvala za pojasnilo!
