### ISSUE TITLE
IB-edavki: kaj delam narobe? 

### ISSUE THREAD

**Issue by u7931** [jamsix/ib-edavki#116]
Zdravo,

Lansko leto mi je uspelo s skripto kreirati poročila iz IBKR v XML za uvoz v edavke. 
Letos sem postopek ponovil (prenos skripte med documents, vnos podatkov v companies in taxpayer) ter v isti direktorij prenesel datoteke za trgovalna leta 2021, 2022, 2023 in 2024 (za prve 3 tedne). Nazivi datotek so: davki21, davki22, davki23 in davki24.
Po zagonu cmd.exe sem vnesel ukaz ib_edavki.py 
Pojavi se sledeči error:
![Slika1](https://github.com/jamsix/ib-edavki/assets/122830701/f00ecaab-e206-4f1a-bef3-da76d3116eb4)

Probal sem še par drugih rešitev, ki so opisane tukaj, pa mi nikakor ne uspe. Želel pa bi upoštevati datotek vseh let trgovanja.
Kaj delam narobe oz. ali obstaja kak drug ukaz za pretvorbo.

Najlepša hvala za pomoč, Uroš

**Comment by jamsix** [comment]
Poskusi `ib_edavki.py davki21 davki22 davki23 davki24`

**Comment by u7931** [comment]
Sem poiskusil, pa mi javi sledeče:
![Slika2](https://github.com/jamsix/ib-edavki/assets/122830701/46195bce-c91a-4fe6-ae4e-29eb2974a207)

**Comment by u7931** [comment]
Drži - dodal sem nekaj podjetij, ki so manjkala. Lahko, da sem se kje zmotil.
Sem ponovno naložil skripto, ohranil originalno datoteko companies.xml in dodal prejšnjo datoteko taxpayer. Pri zagonu z ukazom ib_edavki.py davki21 davki22 davki23 davki24 se izpiše tole:
![Slika3](https://github.com/jamsix/ib-edavki/assets/122830701/1fa09b0d-3c3d-4347-bcd9-366668e0d119)

**Comment by u7931** [comment]
Poiskusil sem še enkrat. Naložil skripto in dodal datoteke po letih - davki21, davki22, davki 23 in davki 24. Originalne datoteke companies nisem.xml nisem spreminjal. V originalni datoteki taxpayer sem samo vnesel svoje podatke. Z enakim ukazom je bil izpis isti kot zgoraj.

**Comment by jamsix** [comment]
Ena od datotek `davki21`, `davki22`, `davki23` ali `davki24` ne obstaja. Verjetno so to v resnici XML datoteke, ampak imaš v Windows skrite končnice?

Poskusi `ib_edavki.py davki21.xml davki22.xml davki23.xml davki24.xml`

Sicer pa prilepi izpis ukaza `dir`, da vidimo kaj je v direktoriju v katerem se nahajaš.

**Comment by u7931** [comment]
Vse napisano drži. V resnici so bile xml datoteke s skritimi končnicami. 
Uspelo mi je generirati vse reporte z ukazom: ib_edavki.py davki21.xml davki22.xml davki23.xml davki24.xml
Hvala za pomoč in skripto, ki nam je v veliko pomoč! Se oddolžim.

**Comment by u7931** [comment]
Prosil bi še za link za donacije.
