### ISSUE TITLE
IBCE -> IBIE merger

### ISSUE THREAD

**Issue by pronebird** [jamsix/ib-edavki#138]
Verjetno bo treba prenoviti skripto ker novi računi se preimenovali z novo predpono:

`U3<id računa>` - IBUK
`U4<id računa>` - IBUK
`U7<id računa>` - IBCE
`U16<id računa>` - IBIE  🆕

Ne vem kako to smo trenutno hendlamo, izgleda tako da ni bo dovolj če preverjamo samo prvi dve črki. Čakam na zaključek migracije da preverim če za res U16 bo tud se pojavila na drugem računu da ugotovim da tista šifra je prava za IBCE.

**Comment by jamsix** [comment]
Te podatke imam za 1x:

IBUK
3xxxxxx
4xxxxxx

IBIE
55xxxxx
56xxxxx
57xxxxx
58xxxxx
59xxxxx
11xxxxxx
16xxxxxx

IBCE
50xxxxx
51xxxxx
52xxxxx
53xxxxx
54xxxxx
6xxxxxx
7xxxxxx
8xxxxxx
9xxxxxx
10xxxxxx

**Comment by pronebird** [comment]
Super hvala za podatki. Verjetno če obravnamo vse skupaj potem ni pomembno kateri account id imamo? Osebno tudi probam obravnati tisti XML-ji ločeno tako da iščem vezo med računi.

**Comment by jamsix** [comment]
Malo sem iz vaje, ampak takole po spominu bi rekel:
- za večino ni potrebno ugotavljat kateri račun je, zaupamo uporabniku, da vnaša relevantne podatke za svoje račune in upoštevamo vse input podatke
- edino za obresti je pomembno, ker je potrebno navesti izplačevalca
- v README je potrebno posodobit tisto sekcijo za generiranje reporta, ki govori o 2021 prenosu iz IBUK na IBCE

**Comment by pronebird** [comment]
Rešeno
