### ISSUE TITLE
Napaka pri pretvorbi za edavke - migriran račun

### ISSUE THREAD

**Issue by sasos90** [jamsix/ib-edavki#140]
Na davkomatu, mi javlja da FlexStatement-u manjka parameter accountID, čeprav mu ne manjka, saj sem preveril XML vsebino.
Imam migriran račun in izbral sem oba računa ko sem poganjal FlexQuery za izvoz podatkov.

Vse sem opravil po navodilih, ampak, ko hočem pretvorit vse 4 datoteke (ali pa tudi samo Doh-KDVP), mi Davkomat vrže napako:
`V FlexStatement manjka parameter accountId. Parameter uporabljamo za ločevanje trgovanj v primeru večjega števila računov.`

Šel sem še enkrat skozi navodila, pa mi ne manjka nič. Je še potrebno narediti kaj drugega za pretvorbo?

lp in hvala!

**Comment by pronebird** [comment]
Pomoje davkomat nima veze s tistim orodjem tu. Tako da jaz bi svetoval naj probaj narediti sporočilo s skripto namesto davkomata in če je enak problem potem pa bomo skupaj iskali rešitev.

**Comment by sasos90** [comment]
Ignorirajte. Namesto xmlja iz IBKRja sem importal Doh KDVP fajl.. :D

**Comment by sasos90** [comment]
Btw @pronebird dobim pa da je davkomat trenutno preobremenjen. Je kaj down?
