### ISSUE TITLE
Issue when switching from long to short in one transaction

### ISSUE THREAD

**Issue by brinkokevin** [jamsix/ib-edavki#15]
The issue appears when you sell more shares than you own, in the exported file openCloseIndicator appears to be "C;O" in those cases.

Example:
Day 1: Buy 100 shares - open long
Day 1: Sell 200 shares - openCloseIndicator = "C;O" switches from long to short in one trade
Day 2: Buy 100 shares - close short

![image](https://user-images.githubusercontent.com/8604658/104820519-738c0800-5835-11eb-9917-7dd32a656a5b.png)
![image](https://user-images.githubusercontent.com/8604658/104821378-b05afd80-583b-11eb-8f2c-d0e7b1ef4504.png)

**Comment by jamsix** [comment]
Hvala, preverim!

**Comment by SamoPP** [comment]
Imam enak izziv.

**Comment by jamsix** [comment]
Closing as it should be solved in #23, @brinkokevin if that won't work for you, please reopen.
