### ISSUE TITLE
Support eToro outputs

### ISSUE THREAD

**Issue by jamsix** [jamsix/ib-edavki#17]
I recently got a few requests to add eToro support besides Interactive Brokers. That would be a nice addition and the code wouldn't mind to get organised a bit and be more flexible in terms of inputs. Unfortunately it is unlikely I'll get that added in time for the 2021 tax season.

The idea is probably to provide an alternate parser to the one made for IB between lines 150 and 425 and put trades data into `mergedTrades` dict. The rest of the code should be the same.

Given that there are multiple interested parties, perhaps a couple of people can group up and code it?

**Comment by masbug** [comment]
Here you go ;)
https://github.com/masbug/etoro-edavki

If you want, you can freely merge the code into a single repo.
Cheers!

**Comment by jamsix** [comment]
@masbug legendary! What do you think about merging projects in time for the next year tax season?

**Comment by masbug** [comment]
I'm all for it :)

**Comment by jamsix** [comment]
Drop me an email -> primoz@outlook.com

**Comment by foozheenc** [comment]
Is it possible to get compatibility for a trading 212?

**Comment by jamsix** [comment]
@foozheenc I'm not excluding the possibility that someone will do that, but core team is unlilkely to do it.

I don't want to get into heated debates and this is my personal opinion, but ... since IB dropped monthly fees in 2021, there is arguably little to no reason why would someone use trading 212 or eToro over IB.
