### ISSUE TITLE
KeyError: 'assetType'

### ISSUE THREAD

**Issue by aljazm** [jamsix/ib-edavki#19]
Hi,

I am getting this error and can't find a way around it. 

Traceback (most recent call last):
  File "c:\Users\user\AppData\Local\Programs\Python\Python39\Scripts\ib-edavki-script.py", line 33, in <module>
    sys.exit(load_entry_point('ib-edavki==1.3.0', 'console_scripts', 'ib-edavki')())
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\ib_edavki.py", line 491, in main
    if trade["assetType"] == "normal" and trade["positionType"] == "long":
KeyError: 'assetType'

The problem are commodities and  options trades.  When deleting that part from the XML export program works as expected. 

Resovled with editing this line (adding cmdty to ignore list):
ignoreAssets = ["CASH", "CMDTY"]

**Comment by jamsix** [comment]
Hey @aljazm you found the solution, great. Added now in eada472. If I understand correctly, IB only offers two `CMDTY` assets, `XAUUSD` gold and `XAGUSD` silver which are both traded tax-free so can be ignored.
