### ISSUE TITLE
Handling Pil - Payment in Lieu

### ISSUE THREAD

**Issue by tinodj** [jamsix/ib-edavki#2]
I have two negative dividents on the short positions in my data. Obviously, FURS is not interested in those. For me solution is just removal from the file, but the code here might be a bit modified to move them to separate file or just skip them. 

More info on this: 
https://ibkr.info/article/42

How the line looks like: 
``` <CashTransaction accountId="U" acctAlias="" model="" currency="USD" fxRateToBase="0.87976" assetCategory="STK" symbol="" description=" PAYMENT IN LIEU OF DIVIDEND (Ordinary Dividend)" conid="" securityID="" securityIDType="" cusip="" isin="" listingExchange="NYSE" underlyingConid="" underlyingSymbol="" underlyingSecurityID="" underlyingListingExchange="" issuer="" multiplier="    1" strike="" expiry="" putCall="" principalAdjustFactor="" dateTime="" settleDate="" amount="-4.8" type="Payment In Lieu Of Dividends" tradeID="" code="" transactionID="" reportDate="" clientReference="" ```

So, I would say skip negative amounts for Doh-Div. 

They expect only positive numbers, here is the definition: ```<xs:pattern value="\d{1,12}(\.\d{1,2})?"/>```

**Comment by jamsix** [comment]
@tinodj for short positions you should have two `CashTransaction` entries, a positive one for a dividend you receive on your borrowed stock and a negative one for a dividend you need to pay to the stock lender. A sum of the two should be 0, is that correct? If so, is the sum you need to report to FURS 0 or a positive valuer of a dividend you've received?

**Comment by tinodj** [comment]
@jamsix in my data I see only one negative CashTransaction as described above. Have no idea why I don't have the positive one, maybe I did something wrong when creating this report from IBKR. 

Regarding the reporting to FURS, I got info that zero should be reported, or it should be just skipped.

**Comment by jamsix** [comment]
@tinodj currently I am summing up all values for a stock in a single day, so if there are two, say -10 and +10 I sum it up in 0 and export 0 in the D-IFI.
Should the right solution here be to do the same, but omit 0 and negative values in the final D-IFI output (i.e. if there is a single negative entry, it will be skipped, if there is a positive and negative entry for same stock on the same day, I add them together and only skip it from the final output if 0 or negative?

**Comment by tinodj** [comment]
@jamsix I think that will be a good solution!

**Comment by jamsix** [comment]
@tinodj fixed in https://github.com/jamsix/ib-edavki/commit/587fb6e96dbc9e2bf55b30f1b43a7c86e96c6428

Also seems I've been reporting wrong dates for dividends, see https://github.com/jamsix/ib-edavki/commit/bdf7c7265d0131b783ddafd1383d53dab0b9796a

Do you mind running it on your data and validate?
