### ISSUE TITLE
What is best way to handle positions with purchase in previous year and closing in the first days of reporting year?

### ISSUE THREAD

**Issue by SamoPP** [jamsix/ib-edavki#21]
Man, I owe you lunch or two... :)

What is the most elegant (lowest effort) way to handle positions that were open, say in December 2019 and closed in January 2020? Obviously in flex reports generated for just 2020 (from 01.01.2020 to 31.12.2020) there are no purchases of a particular financial instrument from 2019 so in DOH-DDVP.xml there is only a sale transaction with a negative F8 (inventory). Would simply generating flex report with part of 2019 where these positions were opened do the trick with potential deletion of buys and sells all closed in 2019 do the trick?

**Comment by ddbk** [comment]
This should work out of the box if you generate flex reports for each year of trading on IB and then list them all as entry arguments for the ib-edavki script like so:

`ib-edavki -y 2020 ib-xml-file-2019.xml ib-xml-file-2020.xml`

**Comment by SamoPP** [comment]
Thanks. This multiyear chaining of input xml files solved the problem.
