### ISSUE TITLE
Problem in getCurrencyRate

### ISSUE THREAD

**Issue by SamoPP** [jamsix/ib-edavki#25]
Looks like instead of using `date` in line 69 of [ib_edavki.py](https://github.com/jamsix/ib-edavki/blob/master/ib_edavki.py)
`rate = float(rates[date][currency])`
it would work better to use `date_that_exists`
`rate = float(rates[date_that_exists][currency])`

**Comment by jamsix** [comment]
Should be fixed in d48140b give it a try!

**Comment by SamoPP** [comment]
Thanks. Would need this change in this branch [close-open](https://github.com/jamsix/ib-edavki/tree/close-open) or even better branch [close-open](https://github.com/jamsix/ib-edavki/tree/close-open) merged into master.

**Comment by SamoPP** [comment]
Works. Thanks.
