### ISSUE TITLE
IB Entity for account UXXXXX not found in flex statement. Check your report settings.

### ISSUE THREAD

**Issue by jamsix** [jamsix/ib-edavki#29]
Script returns `IB Entity for account UXXXXX not found in flex statement. Check your report settings.`

**Comment by jamsix** [comment]
@pronebird Do you have the IB account or one of the white-labels? Can you drop a debug line here and see what you get vs what is in the `ib-affiliates.xml`?
https://github.com/jamsix/ib-edavki/blob/07c6ea18990cdc318a838336aebfc512f09d66f1/generators/doh_obr.py#L41

**Comment by pronebird** [comment]
I have an IB account. It used to be IB-UK. I can certainly print the contents of those things. I think that you're right and the problem that one of accounts didn't exist yet in 2019.

**Comment by pronebird** [comment]
Ok the problem with this code that it doesn't scan all entities before returning `None`.

```
def getIbEntityCode(ibEntities, accountId):
    for ibEntity in ibEntities:
        if (ibEntity["accountId"] == accountId):
            return ibEntity["ibEntity"]

    print("IB Entity for account "
                + accountId + " "
                + "not found in flex statement. "
                + "Check your report settings.")

    return None
```
