### ISSUE TITLE
Short options names are improperly decoded

### ISSUE THREAD

**Issue by pronebird** [jamsix/ib-edavki#3]
I've noticed that long options are properly decoded, i.e:

```MSFT 26JUL19 140.0 C```

But short options are not, i.e displayed as such on e-davki:

```AMD 1910```

The detail view on e-davki displays the full name though:

```AMD 1910      AMD 18OCT19 34.0 C```

Is it intentional?

**Comment by jamsix** [comment]
Yeh @pronebird , that was a bug, fixed in https://github.com/jamsix/ib-edavki/commit/e91678edaabbd9f1b1d7886655b3b5ee278a88a9

Can you run it again on your data and verify?

**Comment by pronebird** [comment]
@jamsix nice, thanks!

I haven't imported the newly generated XML into E-davki as I've already submitted my reports, but I have verified the XML diff between old and new script's output. 

The `Code` field is gone and I remember removing it manually on E-davki to aviod collisions as it seems that E-davki expects the codes to be unique.

```diff
<Name>XLF 30AUG19 25.0 P</Name>
- <Code>XLF   1908</Code>
```
