### ISSUE TITLE
Doh-KDVP.xml created (includes no trades) - "-y 2019"

### ISSUE THREAD

**Issue by tomazb** [jamsix/ib-edavki#34]
Uporabil sem isti Flex query kot za 2020, a sem dal custom range za 2019 obdobje in dobil ustrezen XML od IB. ib-edavki sem pognal s parametrom "-y 2019", a ni notri (v Doh-KDVP.xml) nič podatkov iz 2019.

Tole dobim na izhodu:
Doh-KDVP.xml created (includes no trades)
D-IFI.xml created (includes no trades)
Doh-Div.xml created
Doh-Obr.xml created

**Comment by ddbk** [comment]
Ali so bile delnice, ki so bile prodane v 2019, kupjene v katerem izmed let pred tem, torej da nakupi teh vrednostnih paprijev v IB XML reportu manjkajo? Vidim, da je v tem primeru zgeneriran KDVP prazen in brez obvestila o majkajočih podatkih.

**Comment by tomazb** [comment]
Ne. Ves promet je bil samo v jeseni.

**Comment by ddbk** [comment]
Bi bilo možno dobiti (anonimiziran) flex report ali del njega (lahko na mail), da poskusim reproducirati. Na svojih podatkih ne uspem. Ali pa če lahko poskusi še kdo drug, mogoče @jamsix ? :)

**Comment by jamsix** [comment]
Na mojih podatkih deluje:
```
$ python ib_edavki.py IB-2019.xml -y 2019
Doh-KDVP.xml created (includes trades from years 2019)
D-IFI.xml created (includes trades from years 2019)
Doh-Div.xml created
Doh-Obr.xml created
```
Tudi če bi se se pozicije, ki bi jih zapiral v 2019 odprle v letih prej, bi izdelani XML dokumenti še vedno vsebovali vsaj prodaje (ne pa tudi nakupov). Najbrž bomo res potrebovali anonimiziran flex report, da vidimo v čem je problem.

**Comment by tomazb** [comment]
Sem poslal, a ni bilo odziva.

**Comment by ddbk** [comment]
@tomazb, če si poslal meni, nisem dobil. Lahko še enkrat prosim in bom pogledal, ko utegnem: 3596916+ddbk@users.noreply.github.com?

**Comment by ddbk** [comment]
@tomazb, če si poslal meni, nisem dobil. Lahko še enkrat prosim in bom pogledal, ko utegnem?

**Comment by pronebird** [comment]
I don’t see an option to export trades for former IBUK accounts anymore, so basically anything before 2021 is gone for me but good thing I keep those XML from prior years. 

Either way it would be useful to see the full command used to execute the `ib-edavki` which produces no output.

**Comment by nikegp** [comment]
> I don’t see an option to export trades for former IBUK accounts anymore, so basically anything before 2021 is gone for me but good thing I keep those XML from prior years.

It's there, just the UI is horrible. Click at the account number, then on the filter icon, then select both options and you'll see your old account that you'll be able to select as well as the new one.

**Comment by jamsix** [comment]
@tomazb poskusi z rešitvijo @nikegp , če ne bo delovalo, sporoči.
