### ISSUE TITLE
Warning: IBUK to IBCE/IBLU/IBIE migration in 2021

### ISSUE THREAD

**Issue by jamsix** [jamsix/ib-edavki#39]
There is a good chance your IB account has been "migrated" from the UK to Hungary, Ireland or Luxembourg in 2021. That means you have 2 accounts with potential trades in 2021 and it is thus important you generate the Flex query XML for **both**.

How do you do that?

In the Reports view notice the **U12345678** pill next to the Reports heading. Click on it. Now select both your accounts and press Continue. You should now have two **Uxxxxxxxx** pills next to the Reports heading and the flex query you will generate the XML for both accounts, covering all trades in 2021.

**Comment by pronebird** [comment]
Heads up on dividend report generated for 2021 on IB portal. Mine has wrong withholding tax recorded, although the custom flex query with dividends + withholding tax selected gives the proper breakdown.
