### ISSUE TITLE
Handling withholding tax refunds for dividends

### ISSUE THREAD

**Issue by ddbk** [jamsix/ib-edavki#4]
I have a case where a company paid dividends which were classified in the Dividend Tax Report as `Not Qualified - Return of Capital` for which all withholding tax was refunded. Net withholding tax reported to FURS should therefore be 0, but it's incorrectly calculated in the `Doh-Div.xml` without subtracting the refunded amount.

Looking through the exported xml from IB following the instructions from Readme, withholding tax refund values are missing from that file too. I will try to take some time to research this a bit more and propose a solution.

**Comment by jamsix** [comment]
Thanks, yes please do some research or even submit a PR, covid situation has eaten away all my free time so I am unlikely to do any code changes for the time being :)
