### ISSUE TITLE
V tujini plačani davek

### ISSUE THREAD

**Issue by aljazm** [jamsix/ib-edavki#41]
Zdravo,
Kaj priložite kot dokazilo za Witholding tax. 

xx.xx.xxxx ste oddali Napoved za odmero dohodnine od dividend za leto 2021. Pri pregledu napovedi je bilo ugotovljeno, da uveljavljate v tujini plačan davek in da k napovedi niste priložili ustreznih dokazil, ki izkazujejo podatke o prejemniku dividend, podatke o izplačevalcu dividend, številko računa, znesek dividende in znesek v tujini obračunanega in plačanega davka.

Hvala, A

**Comment by jamsix** [comment]
Osebno oddam IB report s sekcijami:
- Account Information
- Dividends
- Financial Instrument Information

Po mojih izkušnjah je najbolje da pokličeš na FURS in se direktno pogovoriš z referentom/ko.

**Comment by pronebird** [comment]
"Dividend report" pod "Tax reports", dostopen vsako leto od 15.2 naprej.

**Comment by jamsix** [comment]
@pronebird ima prav. Od danes naprej na https://www.interactivebrokers.co.uk/AccountManagement/AmAuthentication?action=TaxReports
