### ISSUE TITLE
po zagonu programa javi več napak

### ISSUE THREAD

**Issue by jazzkos** [jamsix/ib-edavki#46]
Pozdravljeni

Mi nikakor ne uspe zagnati programa. Novo področje zame, laik, dve levi za programe.

Operacijski sistem Win 7, instaliral Python 3.7.3 , updatal pip, instaliral Git , dodal PATH, programi zaznani - verzije vidne na sliki.
Kreirano IB Flex datoteko ib-xml-file-2021 prenesel v ... /scripts/
Zaženem program in mi javi napake vidne na sliki.

Kaj delam narobe?

Hvala za pomoč že vnaprej.

p.s.
Edavki poročila so že napisana. Bi pa lahko preveril/primerjal vsebino z vašo ustvarjeno XML in po potrebi uporabljal pri naslednjem poročanju
![verzije](https://user-images.githubusercontent.com/99198445/152831094-ffca669c-4817-4cc3-b101-76728abecbb0.JPG)
![er1](https://user-images.githubusercontent.com/99198445/152831130-c1669e1a-9e05-4466-a8ce-2df34045d4e0.JPG)
.

**Comment by jamsix** [comment]
Kot kaže datoteke `ib-xml-file-2021` ni v `Scripts` direktoriju, v katerem se trenutno nahajaš? Lahko screenshotneš še izpisek komande `dir`?

**Comment by jazzkos** [comment]
![dir](https://user-images.githubusercontent.com/99198445/153045186-112f1c7a-320f-4e72-bf5d-315fae537e8a.JPG)
![lokacija datoteke](https://user-images.githubusercontent.com/99198445/153045215-42c1f056-ffaa-416f-8051-75e0a2fe0eb5.JPG)

**Comment by jamsix** [comment]
🤷 izgleda kot kak permissions issue v CLIju. Premakni `ib-xml-file-2021` nekam na namizje in poskusi od tam.

**Comment by jazzkos** [comment]
Poizkusil iz namizja 2x, različne poti.
Vrne iste napake.
![er2](https://user-images.githubusercontent.com/99198445/153051220-f4cbef35-548d-4fac-85fa-7aea6ae2ce6e.JPG)

**Comment by jamsix** [comment]
Poskusi z `ib-xml-file-2021.xml`, ne` ib-xml-file-2021`.

**Comment by jazzkos** [comment]
Rešitev na dlani.
Pa sem prepričan, da sem preizkusil tudi to kombinacijo preden sem prosil za pomoč. Očitno nisem.
Se zahvaljujem še enkrat.
