### ISSUE TITLE
Navodila za generiranje reporta v IB mogoče zastarela?

### ISSUE THREAD

**Issue by TineOg** [jamsix/ib-edavki#48]
V interactive brokers mislim da za Activity Flex Query ne obstaja več opcija Custom Date Range. Ali se da kako drugače generirati dokument v strukturi ki ga pričakujete?

Lp,
Tine

**Comment by pronebird** [comment]
Obdobje ni pomembno ko ustvarjaš report. Custom Date Range pa potem ukaži pri izpolnitve reporta.

**Comment by Mult1Hunter** [comment]
Navodila so res depricated v tem delu. Date range izbereš na koncu preden izvedeš dejanski export in ne v kreaciji export templata.

**Comment by TineOg** [comment]
Kreiral PR z popravki
