### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by memberzero** [jamsix/ib-edavki#57]
Bi bil kdo pripravljen napisati konkretno kako uporabiti to skripto. Naložil sem Python in Git, naredil sem izvoz iz IBKR, sedaj pa ne vem kako uporabiti ta program.

**Comment by pronebird** [comment]
Kateri operacijski sistem? Drugač pa navodila za uporabo so tukaj: https://github.com/jamsix/ib-edavki#uporaba

**Comment by memberzero** [comment]
Windows 11 Pro.

Ustavi mi se ko imam export in IBKR in ne vem kaj potem narediti. Imam mapo
"ib-edavki-master" v njej je "setup" in "ib_edavki".

Kam moram vpisati "ib-edavki [-h] [-y report-year] [-t]
ib-xml-file-2021_Kocbek"

Hvala!

V V sob., 12. mar. 2022 ob 12:00 je oseba Andrej Mihajlov <
***@***.***> napisala:

**Comment by pronebird** [comment]
Slovenščina kot tuji jezik, zaradi tega naprej opravicujem, če kaj bo ni jasno, @jamsix kot slovenec bi mogoče bolj jasno to obrazložil.

1. Odpri konzolo (`cmd.exe` oz. "Command Prompt"). 

    Če že imaš Python 3 nameščen na računalniku, za namestitev `ib-edavki` napiši naslednjo vrsto in pritisni ⏎:

    ```
    pip install --upgrade git+https://github.com/jamsix/ib-edavki.git
    ```

2. Če že imaš izvoz iz IBKR, potem v konzolo napiši naslednjo vrsto in pritisni ⏎:

    ```
    cd <MAPA kjer imaš ib-xml-file-2021_Kocbek>
    ```

    naprimer:
    ```
    cd C:\Users\Kocbek
    ```

3. Potem izpolni skripto in pritisni ⏎. Skripta bo ustvarila `taxpayer.xml`.
    ```
    ib-edavki
    ```

4. Odpri `taxpayer.xml`, izpolni osebni podatki in shrani dokument. Lahko ta dokument urediš v "Notepad" ali podobni program za urejanje besedila.

5.  Za uvoz datotek še enkrat izpolni skripto, ampak zdaj tudi posreduj IBKR export XML pa davnčno leto in pritisni ⏎:

    ```
    ib-edavki -y 2021 ib-xml-file-2021_Kocbek.xml
    ```

    Če imaš izvoz za dve leti ali več, posreduj XML za vsako leto, naprimer:

    ```
    ib-edavki -y 2021 ib-xml-file-2020.xml ib-xml-file-2021.xml
    ```

6. Na koncu dobiš 4 XML datoteki (`Doh-KDVP.xml`, `D-IFI.xml`, `Doh-Div.xml`, `Doh-Obr.xml`) za uvoz na e-davki in to je to.

**Comment by memberzero** [comment]
Uspelo, hvala!

V V sob., 12. mar. 2022 ob 12:57 je oseba Andrej Mihajlov <
***@***.***> napisala:
