### ISSUE TITLE
Ne dela

### ISSUE THREAD

**Issue by weiler456** [jamsix/ib-edavki#61]
Vrti krogec v nedogled... v čem bi lahko bila težava?

**Comment by jamsix** [comment]
`ib-edavki` načeloma nima krogcev. Lahko bolj podrobno razložiš kaj si naredil in kje se ti ustavi?

**Comment by weiler456** [comment]
:) pardon. Ni tole implementirano v davkomat? Tam se nič ne zgodi. Povezava je namreč na to stran, zato pišem tukaj.

**Comment by jamsix** [comment]
Ne, lahko da uporabljajo našo kodo, kar je načeloma OK, nismo pa to mi, tako da ne moremo nudit podpore. Najbolje, da se obrneš na njih!

**Comment by weiler456** [comment]
hvala za odgovor. Probam raje po vaše.. če se zatakne javim. Bo pa nekaj gruntanja.

**Comment by easwee** [comment]
Čisto za informacijo in potrditev - deluje 100%, če slediš navodilom.

**Comment by weiler456** [comment]
Zdravo, kot nekomu, ki je prvič odprl cmd :) mi je sicer vseeno vzelo nekaj časa, ampak evo - USPELO! Noro! Hvala! Vse pohvale!
