### ISSUE TITLE
Skripta na davokmat.si ne dela

### ISSUE THREAD

**Issue by reljicandrej** [jamsix/ib-edavki#62]
Živijo,

Aplikacija davkomat.si je super ideja, sledil sem navodilom, naredil XML izvoz, naložil v aplikacijo, ampak melje v nedogled.

Kakšna ideja zakaj ne bi naredilo pretvorbe in samo nalagalo v nedogled?

Hvala!

Andrej

**Comment by jamsix** [comment]
Andrej, `ib-edavki` skripta ni povezana z `davkomat.si`, tako da se boš za podporo moral obrnit na njih.
