### ISSUE TITLE
Kako uporabiti skripto

### ISSUE THREAD

**Issue by reljicandrej** [jamsix/ib-edavki#63]
Živijo,

Sem začetnik in nimam pojma o programiranju.

Naložil sem python, git in pripravil report iz IBKR. Potegnil sem datoteke iz GitHuba.

Kam vpišem kodo, da zaženem skripto?

Vem, da morem vpisat "ib-edavki -y 2022 davki.xml"  (davki.xml je ime reporta)

Probal sem cmd v folderju in "Git Bash here" ampak več kot očitno nimam pojma kaj delam :)

Bi bil hvaležen za pomoč!

**Comment by jamsix** [comment]
1. Odpri mapo v kateri imaš eksportane XML datoteke, desni gumb na miški, Odpri v terminalu.
![Posnetek zaslona_20230111_113452](https://user-images.githubusercontent.com/4974831/211784484-8b1742df-9ab0-4fc9-96bd-ba80184bba96.png)

2. Sledi [navodilom](https://github.com/jamsix/ib-edavki).
![Posnetek zaslona_20230111_113753](https://user-images.githubusercontent.com/4974831/211785508-b48ae7fb-a45c-430a-91a7-4496c687dcc4.png)

**Comment by jamsix** [comment]
1. Odpri mapo v kateri imaš eksportane XML datoteke, desni gumb na miški, Odpri v terminalu.
![Posnetek zaslona_20230111_113452](https://user-images.githubusercontent.com/4974831/211784484-8b1742df-9ab0-4fc9-96bd-ba80184bba96.png)


2. Sledi [navodilom](https://github.com/jamsix/ib-edavki).
![Posnetek zaslona 2023-01-11 113957](https://user-images.githubusercontent.com/4974831/211785773-9b3f245b-6a9c-4b3a-a4a8-1289e47ca75c.png)

**Comment by jamsix** [comment]
Res je, napaka v navodilih, popravljeno (https://github.com/jamsix/ib-edavki/commit/d7903224bb1e068d5a40b7217455de9cf62a6c9d).
