### ISSUE TITLE
Dividende

### ISSUE THREAD

**Issue by nx09** [jamsix/ib-edavki#64]
Živjo, 

prosil bi za pomoč pri dividendah, problem je sledeč:
![image](https://user-images.githubusercontent.com/122683939/212477832-8485e674-2947-48ee-a843-305a8c2d68ce.png)

**Comment by jamsix** [comment]
Živjo,

IB v svojih izpiskih ločeno prikazuje dividende in odvedene davke, zato skripta ta dva podatka poveže na način, da zaporedno išče ujemajočo dividendo z davkom na isti dan. V tem primeru skripti ni uspelo najt izvorno dividendo za ta davek.

Preveri v PDF izpisku z IBja če najdeš ta davek in njemu ustrezajočo dividendo. Če da, je verjetno napaka v skripti. Kaj več pa lahko rečem le, če mi pošlješ `<CashTransactions>` izsek iz XML datoteke, ki si jo generiral v IB -> primoz afna outlook.com

**Comment by jamsix** [comment]
Uporabnik v XML izpisu ni imel dividend, ker mu IB ni dovolil izbrati Dividends.
