### ISSUE TITLE
Dokazilo o plačilu tujega davka

### ISSUE THREAD

**Issue by miharekar** [jamsix/ib-edavki#66]
Najprej najlepša hvala za to orodje!

Imam pa problem pri Doh/Div in mi googlanje ne gre in ne vem kaj je potrebno dodati vlogi. 

Tole mi javlja:
<img width="808" alt="CleanShot 2023-01-21 at 16 16 52@2x" src="https://user-images.githubusercontent.com/986645/213873552-9af32dd0-8029-4645-b17c-56c16d51080a.png">

Any ideas?

Hvala še enkrat!

**Comment by mfilej** [comment]
Pozdravljeni, g. @miharekar! Jaz ponavadi priložim izvoženo poročilo (PDF, CSV, XLS, ... odvisno od brokerja) in do sedaj ni bilo težav.

**Comment by pronebird** [comment]
Okrog 15.2 dobiš dividend report na IBKR. Ta PDF naloži na edavki pa to je to. Ali pa lahko uredi izvoz Flex reporta sam za dividende. Vse eno.

**Comment by miharekar** [comment]
Super, najlepsa hvala!
