### ISSUE TITLE
IB-edavki: kaj delam narobe?

### ISSUE THREAD

**Issue by u7931** [jamsix/ib-edavki#68]
Zdravo,

Kljub temu, da sem brez znanja računalništva, bi se rad nauči uporabljati skripto.
Skripto sem prenesel v direktorij c:\Users\Anonymous\ib-edavki in dodal tudi poročilo iz IBKR z imenom davki.xml (xml je tudi v nazivu datoteke).

Potem sem odprl cmd.exe. in z namenom, da ustvarim datoteko tax_payer.xml vnesel ukaz:
C:\WINDOWS\system32>C:\ib-edavki\ib_edavki.py

Dobil sem izpis:
C:\WINDOWS\system32>C:\ib-edavki\ib_edavki.py
Modify taxpayer.xml and add your data first!
Traceback (most recent call last):
  File "C:\ib-edavki\ib_edavki.py", line 1333, in <module>
    main()
  File "C:\ib-edavki\ib_edavki.py", line 89, in main
    f = open("taxpayer.xml", "w+", encoding="utf-8")
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: 'taxpayer.xml'

C:\WINDOWS\system32>C:\ib-edavki\ib_edavki.py
Modify taxpayer.xml and add your data first!
Traceback (most recent call last):
  File "C:\ib-edavki\ib_edavki.py", line 1333, in <module>
    main()
  File "C:\ib-edavki\ib_edavki.py", line 89, in main
    f = open("taxpayer.xml", "w+", encoding="utf-8")
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: 'taxpayer.xml'

Kaj delam narobe? Hvala!

**Comment by jamsix** [comment]
`ib-edavki` dela z datotekami, ki so v direktoriju, v katerem se trenutno nahajas. Ker je `C:\WINDOWS\system32` sistemski direktorij, ti Windows ne pustijo pisat po njem.

Naredi nov direktorij, npr. `ib-edavki` v `Documents` in pojdi vanj. Nato klikni v naslovno vrstico in vtipkaj `cmd`. Command prompt se ti bo sedaj odprl v tvojem direktoriju.

**Comment by u7931** [comment]
Naredil sem kot napisano, vtipkal cmd, kreiral taxpayer in spremenil podatke. Potem sem zagnal ukaz:
ib_edavki.py -y 2022 ib-xml-file-davki.xml in mi izpiše slednje:

C:\Users\Anonymous\OneDrive - Trigana d.o.o\Documents\ib-edavki>\ib_edavki.py -y 2022 ib-xml-file-davki.xml
'\ib_edavki.py' is not recognized as an internal or external command,
operable program or batch file.

Naziv datoteke iz ibkr je "davki.xml"

Sem kaj preskočil oz. narobe napisal?

**Comment by jamsix** [comment]
Poskusi
`ib_edavki davki.xml`
ali
`C:\ib-edavki\ib_edavki.py davki.xml`

**Comment by u7931** [comment]
Uspelo mi - C:\ib-edavki\ib_edavki.py davki.xml
Doh-KDVP.xml created (includes trades from years 2022)
D-IFI.xml created (includes trades from years )
Doh-Div.xml created
Doh-Obr.xml created

Najlepša hvala za pomoč in podporo!
