### ISSUE TITLE
Bug pri izpolnjevanju oprostitev po mednarodnih pogodbah v Doh-Div

### ISSUE THREAD

**Issue by mihrot** [jamsix/ib-edavki#79]
Podatki za uveljavitev oprostitev po mednarodnih pogodbah se ne izpolnijo v Doh-Div (tag `<ReliefStatement>`). Ugibam, da se problem pojavi le ob namestitvi preko pipa in zato še ni bil opažen. 

Problem je v temle snippetu (189-193 v [ib_edavki.py](https://github.com/jamsix/ib-edavki/blob/master/ib_edavki.py))

    if not os.path.isfile("relief-statements.xml"):
        urllib.request.urlretrieve(
            "https://github.com/jamsix/ib-edavki/raw/master/relief-statements.xml",
            "treaties.xml",
        )

ki referenčno datoteko za pogodbe shrani kot `treaties.xml`. Sledeča koda želi do te datoteke dostopat pod imenom `relief-statements.xml` in je seveda ne najde. Ob preimenovanju `treaties.xml -> relief-statements.xml` koda deluje kot pričakovano.

**Comment by pronebird** [comment]
PR prosim.

**Comment by jamsix** [comment]
Tole sem pa res šalabajzersko spregledal 🤷 
https://github.com/jamsix/ib-edavki/pull/80
