### ISSUE TITLE
Add support for warrants

### ISSUE THREAD

**Issue by pronebird** [jamsix/ib-edavki#8]
At some point in 2020 I held Virgin Galactic warrants (`SPCE WS`), `assetCategory` is `WAR`. 

These are like long dated options, (i.e `SPCE 25OCT24 11.5 C`). So I think the script has to be tweaked to turn warrants into derivatives. 

Warrant lots usually control less underlying, i.e 1 warrant is 1 share, unlike options where 1 call or put is 100 shares of thr underlying, `multiplier` is properly set in XML dump from IBKR so I think we could probably handle it the same way as options, because in theory 1 warrant can control any arbitrary number of shares, depending on the issuer.

That's how the trade looks like in XML:

    <Trade accountId="U304XXXX" accruedInt="0" acctAlias="" assetCategory="WAR" brokerageOrderID="XXXX" buySell="BUY" changeInPrice="0" changeInQuantity="0" clearingFirmID="" closePrice="8.98" conid="389073053" cost="861" currency="USD" cusip="92766K114" dateTime="20200210;112946" description="SPCE 25OCT24 11.5 C" exchOrderId="N/A" exchange="ARCA" expiry="20241025" extExecID="0d.a467.0c.01.0006b7:56003" fifoPnlRealized="0" fxPnl="0" fxRateToBase="1" holdingPeriodDateTime="" ibCommission="-1" ibCommissionCurrency="USD" ibExecID="00010358.5e415559.01.01" ibOrderID="XXXX" isAPIOrder="N" isin="US92766K1144" issuer="" levelOfDetail="EXECUTION" listingExchange="" model="" mtmPnl="38" multiplier="1" netCash="-861" notes="P" openCloseIndicator="O" openDateTime="" orderReference="" orderTime="20200210;112946" orderType="LMT" origOrderID="0" origTradeDate="" origTradeID="" origTradePrice="0" principalAdjustFactor="" proceeds="-860" putCall="" quantity="100" reportDate="20200210" securityID="US92766K1144" securityIDType="ISIN" settleDateTarget="20200212" strike="11.5" symbol="SPCE WS" taxes="0" tradeDate="20200210" tradeID="2690068669" tradeMoney="860" tradePrice="8.6" traderID="" transactionID="12019303431" transactionType="ExchTrade" underlyingConid="388824891" underlyingListingExchange="NYSE" underlyingSecurityID="US92766K1060" underlyingSymbol="SPCE" volatilityOrderLink="" whenRealized="" whenReopened=""/>

SecurityInfo entry:

    <SecurityInfo assetCategory="WAR" code="" conid="389073053" currency="USD" cusip="92766K114" description="SPCE 25OCT24 11.5 C" expiry="20241025" isin="US92766K1144" issueDate="" issuer="" listingExchange="" maturity="" multiplier="1" principalAdjustFactor="" putCall="" securityID="US92766K1144" securityIDType="ISIN" settlementPolicyMethod="Delivery" strike="11.5" subCategory="" symbol="SPCE WS" underlyingCategory="STK" underlyingConid="388824891" underlyingListingExchange="NYSE" underlyingSecurityID="US92766K1060" underlyingSymbol="SPCE"/>

The script seems to work If I add `WAR` to the list of `derivateAssets` ([source](https://github.com/jamsix/ib-edavki/blob/master/ib_edavki.py#L17)).  It looks like warrants in Slovenia are called "nakupni boni", so probably reporting them under "Other" category ("Drugo") is fine. Thoughts?

The generated XML puts together the following entry:

```
<TypeId>PLIFI</TypeId>
<Type>04</Type>
<TypeName>drugo</TypeName>
<Name>SPCE 25OCT24 11.5 C</Name>
<Code>SPCE WS</Code>
```

I think we need to align the output with options, i.e:

```
<TypeId>PLIFI</TypeId>
<Type>04</Type>
<TypeName>drugo</TypeName>
<Name>SPCE [WS?] 25OCT24 11.5 C</Name>
```

The numbers on e-davki look, right but I think the multiplier still has to be handled as there may be warrants with multiple > 1.

Stack trace:

```
ib-edavki -y 2020 U304XXXX-2019.xml U304XXXX-2020.xml               
There is no exchange rate for 20200413, using 20200409
There is no exchange rate for 20200413, using 20200409
Traceback (most recent call last):
  File "/usr/local/bin/ib-edavki", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/ib_edavki.py", line 434, in main
    if trade["assetType"] == "normal" and trade["positionType"] == "long":
KeyError: 'assetType'
```

**Comment by jamsix** [comment]
I'll take a look!

**Comment by pronebird** [comment]
Note: the basic support for warrants have been merged to master except "warrant executions".

**Comment by jamsix** [comment]
Let's close it for now and reopen when we will need that ;)
