### ISSUE TITLE
edavki ignorirajo identifikacijsko številko izplačevalca dividend, če je ta daljša od 12 znakov

### ISSUE THREAD

**Issue by mfilej** [jamsix/ib-edavki#86]
Ravnokar sem to opazil. Precej tujih držav ima identifikacijske oznake daljše od 12.

Kako bi bilo smiselno, da se tukaj program obnaša? Prva stvar, ki mi pride na pamet: odrezati, kar je daljše od 12 znakov.

(Hkrati se sprašujem, če FURS ta podatek sploh potrebuje in če sem brez veze porabil dva dni za iskanje teh podatkov.)

**Comment by jamsix** [comment]
V navodilih za izpolnjevanje Doh-Div FURS ta podatek zahteva, poznam pa primere, ko se je obrazec oddajal brez teh podatkov, pa je odločba vendarle avtomatsko prišla.

Kar je moteče je to, da ob uvozu Doh-Div eDavki sprejmejo oznake daljše od 12, oznaka je v celoti tudi prikazana v vnosnih poljih, ob oddaji pa potem izgine.

Verjetno je res najboljši način ta, da se oznako enostavno skrajša na 12.

**Comment by ddbk** [comment]
Glede na navodila o izpolnjevanju Doh-Div se podatek zahteva za vse tuje izplačevalce, glede na opombe izpisane pod samim obrazcem, pa se podatek zahteva le za izplačevalce s sedežem v drugih EU državah (druga alineja spodaj):

```
* Za izplačevalce, pravne osebe in osebe z dejavnostjo, registrirane v Sloveniji, vnesete le davčno številko, ki jo najdete na obvestilu, naziva in naslova z državo ni potrebno vnašati.
** Za izplačevalce, registrirane v drugih državah članicah EU, vnesite identifikacijsko številko, ki jo te uporabljajo v davčne namene oz. jo najdete na obvestilu, prav tako vnesite tudi naziv in naslov z državo.
```

V [XSD shemi](https://edavki.durs.si/Documents/Schemas/Doh_Div_3.xsd), omejitve maksimalne dolžine tega polja ni, kar pomeni, da gre za napačno implementacijo na strani e-davkov, in iz tega razloga menim, da dolžine ni smiselno omejevati pri izvozu v xml.

**Comment by mfilej** [comment]
Ok, smiselno.

@jamsix Kar se mene tiče lahko tole zapremo.

**Comment by mfilej** [comment]
Mogoče sem prehitro rekel. Edavki me ne spustijo skozi, zaradi manjkajočih številk — včeraj je izgledalo, da to ne bo problem. Poizkusim odrezati na 12, da vidim, če bo tako šlo skozi.

**Comment by jamsix** [comment]
> V [XSD shemi](https://edavki.durs.si/Documents/Schemas/Doh_Div_3.xsd) omejitve maksimalne dolžine tega polja ni, kar pomeni, da gre za napačno implementacijo na strani e-davkov, in iz tega razloga menim, da dolžine ni smiselno omejevati pri izvozu v xml.

Drži, je pa verjetno ideja ib-edavkov olajšat življenje uporabnikom, da ne izgubljajo časa z referentko FURSa, ki bo želela pojasnila. Ona žal ne ve, s kakšnimi težavami se spopadajo uporabniki eDavkov, vidi le, da manjka podatek v formi 🤷

**Comment by pronebird** [comment]
Ali pa `[a-zA-Z0-9]+` ker `\W` pomoje vključuje `_`

**Comment by ddbk** [comment]
Mislim, da sem težavo napačno razumel, ker sem šele zdaj opazil, da e-davki predolgo davčno številko dejansko (tiho) izbrišejo v celoti. To je pa "zanimiv" problem. 🤦‍♂️ Mogoče vredno kontakta (https://edavki.durs.si/EdavkiPortal/openportal/pages/helpandsupport/contact.aspx), v vmesnem času pa se strinjam s predlagano rešitvijo.

**Comment by jamsix** [comment]
Bom povprašal na FURS, ampak v 1 tednu ne bodo zrihtali :)

**Comment by pronebird** [comment]
```
ALTER TABLE `doh_div` 
MODIFY COLUMN `tax_id` varchar("20");
```

<img src="https://media4.giphy.com/media/l0HUjDphISoMMCMPm/giphy.gif?cid=ecf05e47jzmsuwjk4ib0jdybap3y133bf2fc1spkojftypk3&rid=giphy.gif&ct=g">

**Comment by jamsix** [comment]
Hočeš rečt tkole:
<img width="1171" alt="image" src="https://user-images.githubusercontent.com/4974831/221005710-7b9242e4-4a9e-4fa1-b021-e70e5cee1155.png">

**Comment by jamsix** [comment]
Tole smo za enkrat tehnično rešili z https://github.com/jamsix/ib-edavki/pull/89 . Sem pisal na FURS kako in kaj je s to omejitvijo in če bodo v prihodnje kake ustrezne spremembe, lahko omejitev sprostimo.
