### ISSUE TITLE
Cannot find a matching dividend for WITHHOLDING @ 20% ON CREDIT INT FOR NOV-2022 (20221205) of -5.45.

### ISSUE THREAD

**Issue by SamoPP** [jamsix/ib-edavki#92]
ib_edavki mi javljajo tole napako:

`Cannot find a matching dividend for WITHHOLDING @ 20% ON CREDIT INT FOR NOV-2022 (20221205) of -5.45.
Traceback (most recent call last):
  File "/usr/local/bin/ib_edavki", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/ib_edavki.py", line 1195, in main
    closestDividend["taxEUR"] += closestDividendTax
UnboundLocalError: local variable 'closestDividend' referenced before assignment
`

V IB xml-ju imam naslednje (in še mnogo takih):
`<CashTransactions>
<CashTransaction accountId="UXXXXXX" acctAlias="" model="" currency="EUR" fxRateToBase="1.0492" assetCategory="" symbol="" description="WITHHOLDING @ 20% ON CREDIT INT FOR NOV-2022" conid="" securityID="" securityIDType="" cusip="" isin="" listingExchange="" underlyingConid="" underlyingSymbol="" underlyingSecurityID="" underlyingListingExchange="" issuer="" multiplier="0" strike="" expiry="" putCall="" principalAdjustFactor="" dateTime="20221205" settleDate="20221205" amount="-5.45" type="Withholding Tax" tradeID="" code="" transactionID="1527356550" reportDate="20221205" clientReference="" actionID="0" levelOfDetail="DETAIL" serialNumber="" deliveryType="" commodityType="" fineness="0.0" weight="0.0 (null)" />
<CashTransaction accountId="UXXXXXX" acctAlias="" model="" currency="EUR" fxRateToBase="1.0492" assetCategory="" symbol="" description="WITHHOLDING @ 20% ON CREDIT INT FOR OCT-2022" conid="" securityID="" securityIDType="" cusip="" isin="" listingExchange="" underlyingConid="" underlyingSymbol="" underlyingSecurityID="" underlyingListingExchange="" issuer="" multiplier="0" strike="" expiry="" putCall="" principalAdjustFactor="" dateTime="20221205" settleDate="20221205" amount="-0.71" type="Withholding Tax" tradeID="" code="" transactionID="1527356546" reportDate="20221205" clientReference="" actionID="0" levelOfDetail="DETAIL" serialNumber="" deliveryType="" commodityType="" fineness="0.0" weight="0.0 (null)" />
<CashTransaction accountId="UXXXXXX" acctAlias="" model="" currency="EUR" fxRateToBase="1.0492" assetCategory="" symbol="" description="WITHHOLDING @ 20% ON CREDIT INT FOR SEP-2022" conid="" securityID="" securityIDType="" cusip="" isin="" listingExchange="" underlyingConid="" underlyingSymbol="" underlyingSecurityID="" underlyingListingExchange="" issuer="" multiplier="0" strike="" expiry="" putCall="" principalAdjustFactor="" dateTime="20221205" settleDate="20221205" amount="-0.29" type="Withholding Tax" tradeID="" code="" transactionID="1527356558" reportDate="20221205" clientReference="" actionID="0" levelOfDetail="DETAIL" serialNumber="" deliveryType="" commodityType="" fineness="0.0" weight="0.0 (null)" />
`

**Comment by jamsix** [comment]
Nismo navajeni davka na obresti. Naredim en hiter check, da se ti davki ne upoštevajo pri obresti, bo pa potrebno tole bol resno uredit za `Doh-Obr`, ampak za letošnjo sezono davkov ne bo zneslo.

**Comment by jamsix** [comment]
@SamoPP si na IB-IE? Lahko prilepiš tudi CashTransakcije v katerih si dobil obresti? Lahko tudi na primoz afna outlook.com

**Comment by SamoPP** [comment]
> @SamoPP si na IB-IE? Lahko prilepiš tudi CashTransakcije v katerih si dobil obresti?



> Nismo navajeni obresti. Naredim en hiter check, da se ti davki na obresti ne upoštevajo pri dividendah, bo pa potrebno tole bol resno uredit za `Doh-Obr`, ampak za letošnjo sezono davkov ne bo zneslo.

Boste to [#93](https://github.com/jamsix/ib-edavki/pull/93) zmrgali, da uporabimo še danes? Hvala.

**Comment by jamsix** [comment]
Zmergano!

**Comment by jamsix** [comment]
Težav z Doh-Div ne bi smel več imet, bomo pa za naslednjo sezono moral poskrbet, da IB-IE obresti upoštevamo Pri Doh-Obr.
https://github.com/jamsix/ib-edavki/issues/96
