### ISSUE TITLE
Option exercise is not handled properly

### ISSUE THREAD

**Issue by pronebird** [jamsix/ib-edavki#94]
My output is not sorted, but essentially calls bought and exercised, hence option position is closed at _zero_:

![image](https://user-images.githubusercontent.com/704044/221426493-741a452a-cd3e-4d72-9bd2-9fff7a41bc3d.png)

XML for closing position presumably contains the closing price (`closePrice`) which is wrong:

```
<TItem>
<TypeId>PLIFI</TypeId>
<Type>03</Type>
<TypeName>opcija in certifikat</TypeName>
<Name>PDBC 19AUG22 16 C</Name>
<HasForeignTax>false</HasForeignTax>
<TSubItem>
	<Purchase>
		<F1>2022-08-10</F1>
		<F2>A</F2>
		<F3>3.0000</F3>
		<F4>141.4358</F4>
		<F9>false</F9>
	</Purchase>
	<F8>3.0000</F8>
</TSubItem>
<TSubItem>
	<Sale>
		<F5>2022-08-19</F5>
		<F6>3.0000</F6>
		<F7>154.1675</F7>
	</Sale>
	<F8>0.0000</F8>
</TSubItem>
</TItem>
```

I think that it's probably reasonable to assume that in case of option exercise:

1. All long options once exercised should be considered worthless. So that's a loss since premium was paid.
2. All short options once exercised should net full gain in terms of premium received. Sell at {price} x 100 per lot, close at zero. Difference is the gain.

**Comment by pronebird** [comment]
Thinking that this could remedy this issue:
https://github.com/jamsix/ib-edavki/commit/8c1dd48a848f4e07a90c3c90fa1349614638e5ca

**Comment by jamsix** [comment]
This is one of those misteries in life to which we will never gain the right answer.

This is the answer which I got from FURS, which - to me - makes absolutely no common sense.

> Primer 1:
31. avgusta 2021 ste kupili opcijsko pogodbo za nakup ("Call") 100 delnic SPY po ceni 470 USD z
dnevom poteka 19. november 2021 (SPY 19NOV21 470.0 C). Za opcijsko pogodbo ste plačali 315
USD. Na dan poteka je bila delnica SPY ob koncu trgovanja vredna 468,98 USD, torej manj od cene
v opcijski pogodbi, zato je opcijska pogodba potekla ("expire") brez vrednosti in brez nakupa delnice
SPY.
V opisanem primeru pride do avtomatično izvršljive opcije (opcija je potekla, brez vrednosti, brez
nakupa delnic) in ne do njene odsvojitve po ZDDOIFI. Z nakupom delnic, ali z njeno avtomatično
izvršitvijo, zaradi pogodbenega poteka opcije, se namreč uresniči opcijsko upravičenje, ki predstavlja
pogodbeni temelj opcijske pogodbe. Pogodbenega temelja tako v primeru izvršitve opcije samega po
sebi več ni, zato v primeru izvršitve opcije ne gre za odsvojitev v smislu določb ZDDOIFI, na podlagi
katerih se ugotavljajo izgube ali dobički kot razlike med vrednostjo izvedenega finančnega instrumenta
ob odsvojitvi in pridobitvi.
V navedenem primeru ne oddate napovedi za izvedene finančne instrumente.
Primer 2:
1. aprila 2021 sem kupil opcijsko pogodbo ("Call") na vrednost indeksa VIX (VIXW 07APR21 15.0 C)
po kateri sem na dan izvršitve pogodbe, 7. aprila 2021, upravičen do razlike med vrednostjo cene v
pogodbi (15 USD) in vrednostjo indeksa VIX v USD. Opcijska pogodba velja za 100 enot
podrejenega instrumenta, za njen nakup pa sem odštel 400 USD.
Opcijska pogodba se je izvršila ("exercise") na dan poteka, torej 7. aprila 2021, ko je bila vrednost
podrejenega indeksa VIX 17,74 USD, to pomeni da sem bil ob izteku pogodbe "in the money" za
razliko med pogodbeno nakupno ceno 15 USD in aktualno vrednostjo podrejenega indeksa, torej 2,74
USD (x 100 zaradi multiplikatorja). Ob izvršitvi sem prejel 274 USD.
Izvršitev opcije v konkretnem primeru ne zapade obdavčitvi po Zakonu o davku od dobička od
odsvojitve izvedenih finančnih instrumentov - ZDDOIFI. Na podlagi izvršitve opcije po opcijski ceni ste
pridobili delnice, ki se štejejo za kapital po III.6.3.poglavju Zakona o dohodnini – ZDoh-2. Prodajo 
2/3
delnic ste dolžni napovedati v napovedi za odmero dohodnine od dobička od odsvojitve vrednostnih
papirjev in drugih deležev ter investicijskih kuponov.

**Comment by pronebird** [comment]
This is incredible. I read that letter you received in regards of SPY calls that expired OTM. 

This is a loss by any metrics. D-IFI should indicate it and it should offset your gains on derivatives.

Either the laws are stupid or the person who wrote you that has no idea what they talk about or I misunderstand it. I lean towards the latter but you never know.

Common sense tells me that when option expires and you choose to lapse it , the broker should do the following:

1. ITM option (in the money) should be sold by broker, cash should be credited to your account.
2. OTM option (out of the money) should be closed at loss. It's intrinsic value is zero by expiry.

ITM option cannot be forgotten even if you choose not to exercise because it still has some value left.

Account should be credited the remaining value of the contract. Which is what I suppose you have attempted to do here.

Usually I close options before expiry, unless I plan to exercise, I cannot tell what happens when you lapse ITM options, but I would assume that the option should be automatically sold by the end of the day, which should be reflected in the `tradePrice` field just like if you sold it yourself.

Exercise as I said earlier is either full loss of premium long options or max gain in short options.
